#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define SAMPLE_RATE 22050
#define SAMPLE_SIZE (SAMPLE_RATE*3)
#define FORMAT AUDIO_S16SYS
#define CHANNELS 1
#define CHUNKSIZE 1024


#endif // CONFIG_H_INCLUDED
